import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { TopNav } from "./_components/topnav";

// import { Toaster } from "~/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber to Theo on YouTube!",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <div className="grid h-screen grid-rows-[auto,1fr]">
          <TopNav />
          <main className="overflow-y-scroll">{children}</main>
          {modal}
        </div>
        <div id="modal-root" />
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
